[package]
name = "server2"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = { version = "0.34.2"}
chrono = "0.4"


[target. 'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["namedpipeapi", "winbase"] }